# Generated by Django 3.2.20 on 2023-08-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('service_type', models.CharField(choices=[('Gas Leak', 'Gas Leak'), ('Meter Installation', 'Meter Installation'), ('Bill Inquiry', 'Bill Inquiry')], max_length=50)),
                ('description', models.TextField()),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='service_request_files/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_app.customers')),
            ],
        ),
    ]
